<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EPOS.Application\EPOS.Application.csproj" />
    <ProjectReference Include="..\EPOS.Domain\EPOS.Domain.csproj" />
  </ItemGroup>

</Project>
